-- Creating PersonInfo Table
CREATE TABLE PersonInfo (
 PersonID INT PRIMARY KEY,
 PersonName VARCHAR(100) NOT NULL,
 Salary DECIMAL(8,2) NOT NULL,
 JoiningDate DATETIME NULL,
 City VARCHAR(100) NOT NULL,
 Age INT NULL,
 BirthDate DATETIME NOT NULL
);
-- Creating PersonLog Table
CREATE TABLE PersonLog (
 PLogID INT PRIMARY KEY IDENTITY(1,1),
 PersonID INT NOT NULL,
 PersonName VARCHAR(250) NOT NULL,
 Operation VARCHAR(50) NOT NULL,
 UpdateDate DATETIME NOT NULL
);


--Part – A
--1. Create a trigger that fires on INSERT, UPDATE and DELETE operation on the PersonInfo table to display
--a message “Record is Affected.”
CREATE OR ALTER TRIGGER TR_PERSONINFO_INSERT
	ON PersonInfo
	AFTER INSERT,UPDATE,DELETE
AS
BEGIN
	PRINT 'Record is Affected '
END

INSERT INTO PersonInfo VALUES(1,'om',3000,'1999-03-02','MORBI',25,'1980-02-23')



--2. Create a trigger that fires on INSERT, UPDATE and DELETE operation on the PersonInfo table. For that,
--log all operations performed on the person table into PersonLog.

--A) INSERT
CREATE OR ALTER TRIGGER TR_PERSONINFO_INSERT_PERSONLOG
	ON PersonInfo
	AFTER INSERT
AS
BEGIN
	DECLARE @PERSONID INT;
	DECLARE @PERSONNAME VARCHAR(100);
	SELECT @PERSONID = PERSONID FROM INSERTED;
	SELECT @PERSONNAME = PERSONNAME FROM INSERTED;
	INSERT INTO PersonLog
	VALUES(@PERSONID,@PERSONNAME,'INSERT',GETDATE())
END

INSERT INTO PersonInfo VALUES(5,'om1',3000,'1999-03-02','MORBI',25,'1980-02-23')

SELECT * FROM PersonInfo
SELECT * FROM PersonLog

DROP TRIGGER TR_PERSONINFO_INSERT_PERSONLOG



--B)UPDATE
CREATE OR ALTER TRIGGER TR_PERSONINFO_UPDATE_PERSONLOG
	ON PersonInfo
	AFTER UPDATE
AS
BEGIN
	DECLARE @PERSONID INT;
	DECLARE @PERSONNAME VARCHAR(100);
	SELECT @PERSONID = PERSONID FROM INSERTED;
	SELECT @PERSONNAME = PERSONNAME FROM INSERTED;
	INSERT INTO PersonLog
	VALUES(@PERSONID,@PERSONNAME,'UPDATE',GETDATE())
END

UPDATE PersonInfo SET PersonName='ABC' WHERE PersonName = 'OM1';

SELECT * FROM PersonInfo
SELECT * FROM PersonLog

DROP TRIGGER TR_PERSONINFO_UPDATE_PERSONLOG


--C)DELETE
CREATE OR ALTER TRIGGER TR_PERSONINFO_DELETE_PERSONLOG
	ON PersonInfo
	AFTER DELETE
AS
BEGIN
	DECLARE @PERSONID INT;
	DECLARE @PERSONNAME VARCHAR(100);
	SELECT @PERSONID = PERSONID FROM DELETED;
	SELECT @PERSONNAME = PERSONNAME FROM DELETED;
	INSERT INTO PersonLog
	VALUES(@PERSONID,@PERSONNAME,'DELETE',GETDATE())
END

DELETE FROM PersonInfo WHERE PersonID=4

SELECT * FROM PersonInfo
SELECT * FROM PersonLog

DROP TRIGGER TR_PERSONINFO_DELETE_PERSONLOG



--3. Create an INSTEAD OF trigger that fires on INSERT, UPDATE and DELETE operation on the PersonInfo
--table. For that, log all operations performed on the person table into PersonLog.
--A) INSERT
CREATE OR ALTER TRIGGER TR_PERSONINFO_INSERT_PERSONLOG
	ON PersonInfo
	INSTEAD OF INSERT
AS
BEGIN
	DECLARE @PERSONID INT;
	DECLARE @PERSONNAME VARCHAR(100);
	SELECT @PERSONID = PERSONID FROM INSERTED;
	SELECT @PERSONNAME = PERSONNAME FROM INSERTED;
	INSERT INTO PersonLog
	VALUES(@PERSONID,@PERSONNAME,'INSERT',GETDATE())
END

INSERT INTO PersonInfo VALUES(6,'om1',1000,'1999-03-02','MORBI',25,'1980-02-23')

SELECT * FROM PersonInfo
SELECT * FROM PersonLog


DROP TRIGGER TR_PERSONINFO_INSERT_PERSONLOG



--B)UPDATE
CREATE OR ALTER TRIGGER TR_PERSONINFO_UPDATE_PERSONLOG
	ON PersonInfo
	INSTEAD OF UPDATE
AS
BEGIN
	DECLARE @PERSONID INT;
	DECLARE @PERSONNAME VARCHAR(100);
	SELECT @PERSONID = PERSONID FROM INSERTED;
	SELECT @PERSONNAME = PERSONNAME FROM INSERTED;
	INSERT INTO PersonLog
	VALUES(@PERSONID,@PERSONNAME,'UPDATE',GETDATE())
END

UPDATE PersonInfo SET PersonName='ABC' WHERE PersonName = 'OM1';

SELECT * FROM PersonInfo
SELECT * FROM PersonLog

DROP TRIGGER TR_PERSONINFO_UPDATE_PERSONLOG


--C)DELETE
CREATE OR ALTER TRIGGER TR_PERSONINFO_DELETE_PERSONLOG
	ON PersonInfo
	INSTEAD OF DELETE
AS
BEGIN
	DECLARE @PERSONID INT;
	DECLARE @PERSONNAME VARCHAR(100);
	SELECT @PERSONID = PERSONID FROM DELETED;
	SELECT @PERSONNAME = PERSONNAME FROM DELETED;
	INSERT INTO PersonLog
	VALUES(@PERSONID,@PERSONNAME,'DELETE',GETDATE())
END

DELETE FROM PersonInfo WHERE PersonID=4

SELECT * FROM PersonInfo
SELECT * FROM PersonLog

DROP TRIGGER TR_PERSONINFO_DELETE_PERSONLOG
--4. Create a trigger that fires on INSERT operation on the PersonInfo table to convert person name into
--uppercase whenever the record is inserted.
CREATE OR ALTER TRIGGER TR_PERSONINFO_UPPER_PERSONLOG
	ON PersonInfo
	AFTER INSERT
AS
BEGIN
	DECLARE @PERSONID INT;
	DECLARE @PERSONNAME VARCHAR(100);
	SELECT @PERSONID = PERSONID FROM inserted;
	SELECT @PERSONNAME = PERSONNAME FROM inserted;
	UPDATE PersonInfo
	SET PersonName=UPPER(@PERSONNAME)
	WHERE PERSONID=@PersonID
END

SELECT * FROM PersonInfo
SELECT * FROM PersonLog

DROP TRIGGER TR_PERSONINFO_UPPER_PERSONLOG
--5. Create trigger that prevent duplicate entries of person name on PersonInfo table.
CREATE OR ALTER TRIGGER TR_DUPALICATE
	ON PersonInfo
	INSTEAD OF INSERT
AS
BEGIN
	DECLARE @PERSONID INT;
	DECLARE @PERSONNAME VARCHAR(100);
	SELECT @PERSONID = PERSONID FROM inserted;
	SELECT @PERSONNAME = PERSONNAME FROM inserted;
	UPDATE PersonInfo
	SET PersonName=UPPER(@PERSONNAME)
	WHERE PERSONID=@PersonID
END

SELECT * FROM PersonInfo
SELECT * FROM PersonLog

DROP TABLE PersonInfo
DROP TABLE PersonInfo


DROP TRIGGER TR_PERSONINFO_UPPER_PERSONLOG
--6. Create trigger that prevent Age below 18 years.CREATE OR ALTER TRIGGER TR_PERSONINFO_AGE_18
	ON PersonInfo
	AFTER INSERT
AS
BEGIN
	DECLARE @PERSONID INT;
	DECLARE @PERSONNAME VARCHAR(100);
	SELECT @PERSONID = PERSONID FROM inserted;
	SELECT @PERSONNAME = PERSONNAME FROM inserted;
	INSERT INTO PersonLog
	VALUES(@PERSONID,@PERSONNAME,'UPDATE',GETDATE())
END

SELECT * FROM PersonInfo
SELECT * FROM PersonLog

DROP TRIGGER TR_PERSONINFO_UPPER_PERSONLOG

--Part – B
--7. Create a trigger that fires on INSERT operation on person table, which calculates the age and update
--that age in Person table.CREATE OR ALTER TRIGGER tr_CalculateAge
CREATE TRIGGER tr_CalculateAge
ON PersonInfo
AFTER INSERT
AS
BEGIN
    UPDATE PersonInfo
    SET Age = DATEDIFF(YEAR, BirthDate, GETDATE())
    WHERE PersonID IN (SELECT PersonID FROM inserted);
END;

DROP TRIGGER tr_CalculateAge

--8. Create a Trigger to Limit Salary Decrease by a 10%.
CREATE TRIGGER TR_LIMIT_SALARY
ON PersonInfo
AFTER UPDATE
AS
BEGIN
	DECLARE @PERSONID INT,@OLDSALARY INT,@NEWSALARY INT;
	SELECT @PERSONID = PersonID,@OLDSALARY = Salary FROM deleted;
	SELECT @NEWSALARY = Salary FROM inserted WHERE PersonID = @PERSONID

	IF @NEWSALARY < @OLDSALARY * 0.9
	BEGIN
		UPDATE PersonInfo
		SET Salary = @OLDSALARY
		WHERE PersonID = @PERSONID
	END
END

DROP TRIGGER TR_LIMIT_SALARY


--Part – C
--9. Create Trigger to Automatically Update JoiningDate to Current Date on INSERT if JoiningDate is NULL
--during an INSERT.
CREATE TRIGGER TR_JOINGING_DATE
ON PersonInfo
AFTER INSERT
AS
BEGIN
	DECLARE @PERSONID INT;
	SELECT @PERSONID = PersonID FROM inserted 
	UPDATE PersonInfo
	SET JoiningDate = GETDATE()
	FROM PersonInfo 
	WHERE PersonID = @PERSONID

END
--10. Create DELETE trigger on PersonLog table, when we delete any record of PersonLog table it prints
--‘Record deleted successfully from PersonLog’.
CREATE OR ALTER TRIGGER tr_DeleteMessage
ON PersonLog
AFTER DELETE
AS
BEGIN
    PRINT 'Record deleted successfully from PersonLog.'
END;

SELECT * FROM PersonInfo